import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navber from "./components";
import Wrapped from "./components/shared/wrapped";

const inter = Inter({ subsets: ["latin"],weight:["400","500","700","900"] });

export const metadata: Metadata = {
  title: "Dine Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

       <Wrapped>
        
        <Navber/> 
       
        {children}

       </Wrapped>
        
        </body>
    </html>
  );
}
